version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    depends_on:
      - mongo
    environment:
      # You can override these in a .env file
      MONGO_URI: mongodb://root:example@mongo:27017/sparkvote?authSource=admin
      NODE_ENV: production
      # Add other secrets as needed (JWT_SECRET, GEMINI_API_KEY, etc.)
    env_file:
      - .env
    ports:
      - "80:80"
      - "3000:3000"
    restart: always
    # Uncomment if you want to mount code for live reload in dev
    # volumes:
    #   - ./backend:/app/backend
    #   - ./frontend:/app/frontend

volumes:
  mongo-data: 